name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup and Build
        run: |
          mkdir -p /root/ros2_ws/src
          rsync -av ./ /root/ros2_ws/src/mypkg/
          cd /root/ros2_ws
          
          apt-get update && apt-get install -y python3-pip
          rosdep update
          rosdep install -i --from-path src --rosdistro humble -y || true

          chmod +x ./src/mypkg/test/test.bash
          bash -xv ./src/mypkg/test/test.bash /root

