name: test
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Python dependencies
        run: |
          apt-get update
          apt-get install -y python3-pip
          pip install psutil

      - name: Build and Test with test.bash
        run: |
          mkdir -p /root/ros2_ws/src/mypkg
          rsync -av ./ /root/ros2_ws/src/mypkg/
          cd /root/ros2_ws

          rosdep update
          rosdep install --from-paths src --ignore-src --rosdistro humble -y

          chmod +x src/mypkg/test/test.bash
          bash src/mypkg/test/test.bash /root

