name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup and Build
        shell: bash
        run: |
          set -e
          mkdir -p /root/ros2_ws/src
          rsync -av ./ /root/ros2_ws/src/mypkg/
          cd /root/ros2_ws

          apt-get update && apt-get install -y python3-pip python3-colcon-common-extensions

          pip3 install psutil
          source /opt/ros/humble/setup.bash
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y --rosdistro humble

          chmod +x ./src/mypkg/test/test.bash
          bash ./src/mypkg/test/test.bash /root


      - name: Post-Build Cleanup
        run: apt-get clean

